buildscript {
    repositories { mavenCentral() }
}

plugins {
    id 'java-library'
	id 'com.gradleup.shadow' version '9.3.2'
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}

/* 'api' allows the dependency to be exposed to consumers (ie. other projects that depend on this one) while implementation hides it. */
dependencies {
	// Use JUnit Jupiter for testing.
    testImplementation "org.junit.jupiter:junit-jupiter:${project.junit_jupiter_version}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation "io.javalin:javalin:${project.javalin_version}"
    implementation "com.github.Niwer1525:Queryon:${project.queryon_version}"

	implementation "com.google.code.findbugs:jsr305:${project.jrs_version}" // Javax Annotations for JDA
	implementation "net.dv8tion:JDA:${project.JDA_version}"

	implementation "com.google.code.gson:gson:${project.gson_version}"
    implementation "ch.qos.logback:logback-classic:${project.logback_version}" // JDA & Javalin are using this
	implementation "com.github.Niwer1525:Lumen:${project.lumen_version}"
	implementation "de.mkammerer:argon2-jvm:${project.argon2_version}"
	implementation "de.mkammerer:argon2-jvm-nolibs:${project.argon2_version}"
	implementation "com.stripe:stripe-java:${project.stripe_version}"
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

tasks.named('test') {
    useJUnitPlatform() // Use JUnit Platform for unit tests.
	systemProperty 'net.bytebuddy.experimental', 'true'
}

/* Generate JAR */
jar {
	duplicatesStrategy 'exclude'
   	manifest { attributes([ "Main-Class": "niwer.photon.PhotonEngine" ]) }
}

/* Add all dependcies to the jar */
shadowJar {
	mergeServiceFiles()
	// minimize { // TODO minimize cause issues when built (production env.) for logging libs (Logback, SLF4J, etc.)
    //     exclude(dependency('org.xerial:sqlite-jdbc:.*'))
    // }
	archiveClassifier.set('')
}
tasks.build.dependsOn shadowJar