buildscript {
    repositories { mavenCentral() }
}

plugins {
    id 'java-library'
	id 'com.gradleup.shadow' version '9.3.2'
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}

/* 'api' allows the dependency to be exposed to consumers (ie. other projects that depend on this one) while implementation hides it. */
dependencies {
	// Use JUnit Jupiter for testing.
    testImplementation "org.junit.jupiter:junit-jupiter:${project.junit_jupiter_version}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation "io.javalin:javalin:${project.javalin_version}"
    implementation "com.github.Niwer1525:Queryon:${project.queryon_version}"

	implementation "com.google.code.findbugs:jsr305:${project.jrs_version}" // Javax Annotations for JDA
	implementation "net.dv8tion:JDA:${project.JDA_version}"

	api "com.google.code.gson:gson:${project.gson_version}"
    api "ch.qos.logback:logback-classic:${project.logback_version}" // JDA & Javalin are using this
	api "com.github.Niwer1525:Lumen:${project.lumen_version}"

    /* SHADOWING */
    shadow "io.javalin:javalin:${project.javalin_version}"
	shadow "com.github.Niwer1525:Queryon:${project.queryon_version}"
	
    shadow "com.google.code.findbugs:jsr305:${project.jrs_version}" // Javax Annotations for JDA
	shadow "net.dv8tion:JDA:${project.JDA_version}"

	shadow "com.google.code.gson:gson:${project.gson_version}"
    shadow "ch.qos.logback:logback-classic:${project.logback_version}" // JDA & Javalin are using this
	shadow "com.github.Niwer1525:Lumen:${project.lumen_version}"

	// Stripe SDK
	implementation "com.stripe:stripe-java:20.0.0"
	shadow "com.stripe:stripe-java:20.0.0"
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

tasks.named('test') {
    useJUnitPlatform() // Use JUnit Platform for unit tests.
	systemProperty 'net.bytebuddy.experimental', 'true'
}

/* Generate JAR */
jar {
	duplicatesStrategy 'exclude'
   	manifest { attributes([ "Main-Class": "niwer.photon.PhotonEngine" ]) }
}

/* Add all dependcies to the jar */
shadowJar {
	minimize()
   	configurations = [project.configurations.shadow]
	archiveFileName = "network.jar"
	archiveClassifier.set('')
}
tasks.build.dependsOn shadowJar