org.gradle.configuration-cache=true

junit_jupiter_version=5.12.1

queryon_version=v1.1.2
lumen_version=v1.0.5
gson_version=2.13.2
javalin_version=7.1.0
JDA_version=6.3.0
jrs_version=3.0.2
logback_version=1.4.8
gson_version=2.8.8
argon2_version=2.11
stripe_version=20.0.0
simple_java_mail_version=9.3.2